import type { Metadata } from "next";
import Menu from '@/src/menu.tsx';
import Footer from '@/src/footer.tsx';

export const metadata: Metadata = {
  title: "Domus Solis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
      <Menu /> 
      {children}
      <Footer/>
      </>
  );
}
